# Generated by Django 4.2 on 2026-05-29 23:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('suspected_cause', models.CharField(blank=True, max_length=100)),
                ('vet_consulted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_logs', to='flocks.flock')),
            ],
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('feed_type', models.CharField(max_length=50)),
                ('feed_brand', models.CharField(blank=True, max_length=50)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_naira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='flocks.flock')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('medication', 'Medication'), ('labour', 'Labour'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount_naira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_logs', to='flocks.flock')),
            ],
        ),
        migrations.CreateModel(
            name='EggProductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('eggs_collected', models.IntegerField()),
                ('cracked_eggs', models.IntegerField(default=0)),
                ('eggs_sold', models.IntegerField(default=0)),
                ('revenue_naira', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_logs', to='flocks.flock')),
            ],
        ),
    ]
