# Generated by Django 4.2 on 2026-07-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0002_alter_flock_current_count'),
        ('vaccines', '0005_seed_common_drugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateField(auto_now_add=True)),
                ('bird_age_weeks', models.PositiveIntegerField()),
                ('season', models.CharField(choices=[('dry', 'Dry'), ('rainy', 'Rainy')], max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('days_since_last_vaccination', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_distress', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('lethargy', models.BooleanField(default=False)),
                ('reduced_feed_intake', models.BooleanField(default=False)),
                ('leg_weakness', models.BooleanField(default=False)),
                ('sudden_death_count', models.PositiveIntegerField(default=0)),
                ('observation_type', models.CharField(choices=[('sick_check', 'Sick Check'), ('death_log', 'Death Log')], max_length=20)),
                ('risk_label', models.CharField(blank=True, max_length=50)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_observations', to='flocks.flock')),
                ('recent_medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccines.drug')),
            ],
        ),
    ]
