# Generated by Django 4.2 on 2026-05-29 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification')], default='sms', max_length=10)),
                ('notification_type', models.CharField(choices=[('harvest', 'Harvest Ready'), ('vaccine', 'Vaccine Reminder'), ('mortality', 'Mortality Alert'), ('summary', 'Weekly Summary'), ('overdue', 'Overdue Vaccine')], max_length=20)),
                ('message', models.TextField()),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
