# Generated by Django 4.2 on 2026-05-29 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
                ('bird_type', models.CharField(choices=[('broiler', 'Broiler'), ('layer', 'Layer'), ('cockerel', 'Cockerel'), ('turkey', 'Turkey'), ('duck', 'Duck')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('housing_type', models.CharField(choices=[('deep_litter', 'Deep Litter'), ('battery_cage', 'Battery Cage'), ('free_range', 'Free Range')], default='deep_litter', max_length=20)),
                ('initial_count', models.IntegerField()),
                ('current_count', models.IntegerField(editable=False)),
                ('arrival_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('harvested', 'Harvested'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
