# Generated by Django 4.2 on 2026-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
    ]
