# Generated by Django 4.2 on 2026-05-29 23:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=100)),
                ('dose_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_schedules', to='flocks.flock')),
            ],
        ),
    ]
