# Generated by Django 4.2 on 2026-07-05 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_alter_flock_current_count'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('drug_type', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('vitamin', 'Vitamin/Supplement'), ('coccidiostat', 'Coccidiostat'), ('dewormer', 'Dewormer'), ('vaccine', 'Vaccine'), ('other', 'Other')], max_length=20)),
                ('default_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_unit', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_given', models.DateField()),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('quantity_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_logs', to='vaccines.drug')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='flocks.flock')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='drug',
            field=models.ForeignKey(blank=True, limit_choices_to={'drug_type': 'vaccine'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_schedules', to='vaccines.drug'),
        ),
    ]
