# Generated by Django 4.2 on 2026-07-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_backfill_drug_from_vaccine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='vaccine_name',
        ),
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='drug',
            field=models.ForeignKey(limit_choices_to={'drug_type': 'vaccine'}, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_schedules', to='vaccines.drug'),
        ),
    ]
